# THEME
import = ["~/.config/alacritty/themes/eldritch.toml"]

live_config_reload = true

[cursor.style]
blinking = "Off"
shape = "Block"

[colors.cursor]
cursor = "#FFFFFF"
text = "#000000"

[env]
TERM = "xterm-256color"

[font]
size = 20

# For CaskaydiaCove Nerd Font
# [font.bold]
# family = "CaskaydiaCove Nerd Font Mono"
# style = "SemiLight"
#
# [font.italic]
# family = "CaskaydiaCove Nerd Font Mono"
# style = "Light Italic"
#
# [font.normal]
# family = "CaskaydiaCove Nerd Font Mono"
# style = "Light"

# [font.offset]
# x = 0
# y = 0

# For JetBrains Fonts
[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Thin Italic"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Thin"

[mouse]
hide_when_typing = true

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[shell]
program = "/bin/zsh"

[window]
decorations = "Buttonless"
dynamic_title = true
startup_mode = "Maximized"

# [window.dimensions]
# columns = 160
# lines = 80

[window.padding]
x = 0
y = 0
